name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Login to GitHub Container Registry
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/mwcb:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/mwcb:${{ github.sha }}
    
    - name: Build and push to GitHub Container Registry
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/mwcb:latest
          ghcr.io/${{ github.repository_owner }}/mwcb:${{ github.sha }}