name: Monthly Base Image Update

on:
  schedule:
    - cron: '0 0 1 * *'  # First day of each month at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push with updated base image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/mereheze-wiki-contributor:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/mereheze-wiki-contributor:monthly-${{ github.run_id }}
          ghcr.io/${{ github.repository_owner }}/mereheze-wiki-contributor:latest
          ghcr.io/${{ github.repository_owner }}/mereheze-wiki-contributor:monthly-${{ github.run_id }}