name: Monthly Base Image Update

on:
  schedule:
    - cron: '0 0 1 * *'  # First day of each month at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/mereheze-wiki-contributor
        tags: |
          type=raw,value=latest,enable={{is_default}} # Only tag 'latest' on the main branch
          type=sha
          type=ref,event=tag,enable=true,prefix= # Adds the Git tag (e.g., v1.1)
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push with updated base image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/mereheze-wiki-contributor:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/mereheze-wiki-contributor:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/mereheze-wiki-contributor:latest
          ghcr.io/${{ github.repository_owner }}/mereheze-wiki-contributor:${{ github.sha }}

    - name: Update Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: danutzzzzz/mereheze-wiki-contributor # Replace with your actual repo
        # Optional: Use your GitHub repo description as the short description on Docker Hub
        short-description: ${{ github.event.repository.description }}
        # Optional: If your README is not at the root, specify the path
        # readme-filepath: ./docs/README.md 